# Generated by Django 5.2.7 on 2025-10-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_botmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='chat_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
