# Generated by Django 5.2.7 on 2025-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_telegramsummary_alter_usermessage_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
