# Generated by Django 5.2.7 on 2025-10-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_usermessage_chat_id_alter_usermessage_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
