# Generated by Django 5.2.7 on 2025-10-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_usermessage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
