# Generated by Django 5.2.7 on 2025-10-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_botmessage_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTelegramMessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
